-- Taskira upgrade snapshot through 023_sprints.sql.
-- Generated by server/scripts/create-db-snapshot.mjs; do not edit manually.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6


--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--





--
-- Name: activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    issue_id uuid NOT NULL,
    actor_id uuid NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: attachments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attachments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    issue_id uuid NOT NULL,
    uploaded_by uuid,
    filename text NOT NULL,
    content_type text NOT NULL,
    byte_size bigint NOT NULL,
    sha256 text NOT NULL,
    storage_driver text NOT NULL,
    storage_key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT attachments_byte_size_check CHECK ((byte_size > 0)),
    CONSTRAINT attachments_storage_driver_check CHECK ((storage_driver = ANY (ARRAY['local'::text, 's3'::text])))
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    actor_id uuid,
    action text NOT NULL,
    entity text NOT NULL,
    entity_id uuid,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;


--
-- Name: checklist_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checklist_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    issue_id uuid NOT NULL,
    text text NOT NULL,
    done boolean DEFAULT false NOT NULL,
    "position" integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    issue_id uuid NOT NULL,
    author_id uuid NOT NULL,
    body text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT comments_body_check CHECK (((char_length(body) >= 1) AND (char_length(body) <= 2000)))
);


--
-- Name: custom_field_values; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_field_values (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    custom_field_id uuid NOT NULL,
    issue_id uuid NOT NULL,
    value text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: custom_fields; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.custom_fields (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    name text NOT NULL,
    field_type text NOT NULL,
    options jsonb DEFAULT '[]'::jsonb NOT NULL,
    "position" integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT custom_fields_field_type_check CHECK ((field_type = ANY (ARRAY['text'::text, 'number'::text, 'select'::text, 'checkbox'::text, 'date'::text])))
);


--
-- Name: department_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department_members (
    department_id uuid NOT NULL,
    user_id uuid NOT NULL,
    source text DEFAULT 'ldap'::text NOT NULL,
    synced_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT department_members_source_check CHECK ((source = ANY (ARRAY['ldap'::text, 'manual'::text])))
);


--
-- Name: departments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.departments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    ldap_group_dn text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: issue_collaborators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.issue_collaborators (
    issue_id uuid NOT NULL,
    user_id uuid NOT NULL,
    added_by uuid,
    added_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: issue_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.issue_links (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    issue_id uuid NOT NULL,
    linked_issue_id uuid NOT NULL,
    link_type text NOT NULL,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT issue_links_link_type_check CHECK ((link_type = ANY (ARRAY['relates'::text, 'blocks'::text]))),
    CONSTRAINT issue_links_not_self CHECK ((issue_id <> linked_issue_id))
);


--
-- Name: issue_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.issue_templates (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    name text NOT NULL,
    type_id text NOT NULL,
    priority_id text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    status_id uuid,
    "position" integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT issue_templates_priority_id_check CHECK ((priority_id = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text]))),
    CONSTRAINT issue_templates_type_id_check CHECK ((type_id = ANY (ARRAY['task'::text, 'bug'::text, 'request'::text])))
);


--
-- Name: issue_watchers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.issue_watchers (
    issue_id uuid NOT NULL,
    user_id uuid NOT NULL
);


--
-- Name: issues; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.issues (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    num integer NOT NULL,
    key text NOT NULL,
    title text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    type_id text NOT NULL,
    status_id uuid NOT NULL,
    priority_id text NOT NULL,
    assignee_id uuid,
    reporter_id uuid NOT NULL,
    epic_id uuid,
    color text,
    t_start integer,
    t_span integer,
    labels text[] DEFAULT '{}'::text[] NOT NULL,
    rank double precision DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    due_date date,
    done_at timestamp with time zone,
    archived_at timestamp with time zone,
    complexity text,
    parent_id uuid,
    sprint_id uuid,
    CONSTRAINT issues_complexity_check CHECK ((complexity = ANY (ARRAY['simple'::text, 'medium'::text, 'hard'::text]))),
    CONSTRAINT issues_description_check CHECK ((char_length(description) <= 5000)),
    CONSTRAINT issues_parent_not_self CHECK ((parent_id <> id)),
    CONSTRAINT issues_priority_id_check CHECK ((priority_id = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text]))),
    CONSTRAINT issues_title_check CHECK (((char_length(title) >= 1) AND (char_length(title) <= 250))),
    CONSTRAINT issues_type_id_check CHECK ((type_id = ANY (ARRAY['task'::text, 'bug'::text, 'request'::text])))
);


--
-- Name: COLUMN issues.complexity; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.issues.complexity IS 'Простая шкала сложности задачи (не Scrum story points). NULL — не оценена.';


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    type text NOT NULL,
    actor_id uuid,
    project_id uuid,
    issue_id uuid,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    read_at timestamp with time zone,
    email_state text DEFAULT 'pending'::text NOT NULL,
    email_tries smallint DEFAULT 0 NOT NULL,
    dismissed_at timestamp with time zone,
    CONSTRAINT notifications_email_state_check CHECK ((email_state = ANY (ARRAY['pending'::text, 'sent'::text, 'skipped'::text, 'failed'::text]))),
    CONSTRAINT notifications_type_check CHECK ((type = ANY (ARRAY['issue.assigned'::text, 'issue.comment'::text, 'issue.mention'::text, 'issue.status'::text, 'issue.collaborator'::text, 'project.member'::text])))
);


--
-- Name: project_counters; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_counters (
    project_id uuid NOT NULL,
    next_num integer DEFAULT 1 NOT NULL,
    CONSTRAINT project_counters_next_num_check CHECK ((next_num > 0))
);


--
-- Name: project_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project_members (
    project_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    added_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT project_members_role_check CHECK ((role = ANY (ARRAY['manager'::text, 'employee'::text, 'viewer'::text])))
);


--
-- Name: projects; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.projects (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    key text NOT NULL,
    name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    department_id uuid NOT NULL,
    is_shared boolean DEFAULT false NOT NULL,
    sprints_enabled boolean DEFAULT false NOT NULL
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    name text NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: sprints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sprints (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    name text NOT NULL,
    goal text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'future'::text NOT NULL,
    start_date date,
    end_date date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT sprints_status_check CHECK ((status = ANY (ARRAY['future'::text, 'active'::text, 'completed'::text])))
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    username text NOT NULL,
    password_hash text,
    name text NOT NULL,
    initials text DEFAULT ''::text NOT NULL,
    color text DEFAULT '#0B5FD9'::text NOT NULL,
    job_role text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    global_role text DEFAULT 'member'::text NOT NULL,
    auth_source text DEFAULT 'local'::text NOT NULL,
    ldap_dn text,
    email text,
    notify_prefs jsonb DEFAULT '{}'::jsonb NOT NULL,
    tokens_valid_from timestamp with time zone,
    CONSTRAINT users_auth_source_check CHECK ((auth_source = ANY (ARRAY['local'::text, 'ldap'::text]))),
    CONSTRAINT users_global_role_check CHECK ((global_role = ANY (ARRAY['admin'::text, 'member'::text]))),
    CONSTRAINT users_local_has_password CHECK (((auth_source <> 'local'::text) OR (password_hash IS NOT NULL)))
);


--
-- Name: COLUMN users.tokens_valid_from; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.tokens_valid_from IS 'Токены, выданные до этого момента, недействительны (выход, смена пароля). NULL — не отзывались.';


--
-- Name: workflow_statuses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_statuses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    sid text NOT NULL,
    name text NOT NULL,
    category text NOT NULL,
    "position" integer DEFAULT 0 NOT NULL,
    CONSTRAINT workflow_statuses_category_check CHECK ((category = ANY (ARRAY['todo'::text, 'inprogress'::text, 'done'::text])))
);


--
-- Name: workflow_transitions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_transitions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    project_id uuid NOT NULL,
    from_status_id uuid NOT NULL,
    to_status_id uuid NOT NULL,
    CONSTRAINT workflow_transitions_check CHECK ((from_status_id <> to_status_id))
);


--
-- Name: audit_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log ALTER COLUMN id SET DEFAULT nextval('public.audit_log_id_seq'::regclass);


--
-- Name: activity activity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity
    ADD CONSTRAINT activity_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_storage_driver_storage_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_storage_driver_storage_key_key UNIQUE (storage_driver, storage_key);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: checklist_items checklist_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_items
    ADD CONSTRAINT checklist_items_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: custom_field_values custom_field_values_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_field_values
    ADD CONSTRAINT custom_field_values_pkey PRIMARY KEY (id);


--
-- Name: custom_field_values custom_field_values_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_field_values
    ADD CONSTRAINT custom_field_values_uniq UNIQUE (custom_field_id, issue_id);


--
-- Name: custom_fields custom_fields_name_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_fields
    ADD CONSTRAINT custom_fields_name_uniq UNIQUE (project_id, name);


--
-- Name: custom_fields custom_fields_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_fields
    ADD CONSTRAINT custom_fields_pkey PRIMARY KEY (id);


--
-- Name: department_members department_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_members
    ADD CONSTRAINT department_members_pkey PRIMARY KEY (department_id, user_id);


--
-- Name: departments departments_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_name_key UNIQUE (name);


--
-- Name: departments departments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.departments
    ADD CONSTRAINT departments_pkey PRIMARY KEY (id);


--
-- Name: issue_collaborators issue_collaborators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_collaborators
    ADD CONSTRAINT issue_collaborators_pkey PRIMARY KEY (issue_id, user_id);


--
-- Name: issue_links issue_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_links
    ADD CONSTRAINT issue_links_pkey PRIMARY KEY (id);


--
-- Name: issue_links issue_links_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_links
    ADD CONSTRAINT issue_links_uniq UNIQUE (issue_id, linked_issue_id, link_type);


--
-- Name: issue_templates issue_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_templates
    ADD CONSTRAINT issue_templates_pkey PRIMARY KEY (id);


--
-- Name: issue_watchers issue_watchers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_watchers
    ADD CONSTRAINT issue_watchers_pkey PRIMARY KEY (issue_id, user_id);


--
-- Name: issues issues_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_key_key UNIQUE (key);


--
-- Name: issues issues_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_pkey PRIMARY KEY (id);


--
-- Name: issues issues_project_id_num_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_project_id_num_key UNIQUE (project_id, num);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: project_counters project_counters_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_counters
    ADD CONSTRAINT project_counters_pkey PRIMARY KEY (project_id);


--
-- Name: project_members project_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_pkey PRIMARY KEY (project_id, user_id);


--
-- Name: projects projects_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_key_key UNIQUE (key);


--
-- Name: projects projects_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (name);


--
-- Name: sprints sprints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprints
    ADD CONSTRAINT sprints_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: workflow_statuses workflow_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_statuses
    ADD CONSTRAINT workflow_statuses_pkey PRIMARY KEY (id);


--
-- Name: workflow_statuses workflow_statuses_project_id_sid_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_statuses
    ADD CONSTRAINT workflow_statuses_project_id_sid_key UNIQUE (project_id, sid);


--
-- Name: workflow_transitions workflow_transitions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transitions
    ADD CONSTRAINT workflow_transitions_pkey PRIMARY KEY (id);


--
-- Name: workflow_transitions workflow_transitions_project_id_from_status_id_to_status_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transitions
    ADD CONSTRAINT workflow_transitions_project_id_from_status_id_to_status_id_key UNIQUE (project_id, from_status_id, to_status_id);


--
-- Name: departments_ldap_group_dn_uk; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX departments_ldap_group_dn_uk ON public.departments USING btree (lower(ldap_group_dn)) WHERE (ldap_group_dn IS NOT NULL);


--
-- Name: idx_activity_issue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_issue ON public.activity USING btree (issue_id, created_at);


--
-- Name: idx_attachments_issue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attachments_issue ON public.attachments USING btree (issue_id);


--
-- Name: idx_audit_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_actor ON public.audit_log USING btree (actor_id);


--
-- Name: idx_audit_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_created ON public.audit_log USING btree (created_at DESC);


--
-- Name: idx_checklist_items_issue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_checklist_items_issue ON public.checklist_items USING btree (issue_id, "position");


--
-- Name: idx_comments_issue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_comments_issue ON public.comments USING btree (issue_id, created_at);


--
-- Name: idx_custom_field_values_issue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_custom_field_values_issue ON public.custom_field_values USING btree (issue_id);


--
-- Name: idx_custom_fields_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_custom_fields_project ON public.custom_fields USING btree (project_id, "position");


--
-- Name: idx_department_members_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_department_members_user ON public.department_members USING btree (user_id);


--
-- Name: idx_issue_collaborators_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issue_collaborators_user ON public.issue_collaborators USING btree (user_id);


--
-- Name: idx_issue_links_issue; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issue_links_issue ON public.issue_links USING btree (issue_id);


--
-- Name: idx_issue_links_linked; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issue_links_linked ON public.issue_links USING btree (linked_issue_id);


--
-- Name: idx_issue_templates_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issue_templates_project ON public.issue_templates USING btree (project_id, "position");


--
-- Name: idx_issues_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_active ON public.issues USING btree (project_id, status_id, rank) WHERE (archived_at IS NULL);


--
-- Name: idx_issues_archive_candidates; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_archive_candidates ON public.issues USING btree (done_at) WHERE ((done_at IS NOT NULL) AND (archived_at IS NULL));


--
-- Name: idx_issues_assignee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_assignee ON public.issues USING btree (assignee_id);


--
-- Name: idx_issues_done_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_done_at ON public.issues USING btree (project_id, done_at DESC) WHERE (done_at IS NOT NULL);


--
-- Name: idx_issues_due_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_due_date ON public.issues USING btree (due_date) WHERE (due_date IS NOT NULL);


--
-- Name: idx_issues_epic; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_epic ON public.issues USING btree (epic_id);


--
-- Name: idx_issues_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_parent ON public.issues USING btree (parent_id) WHERE (parent_id IS NOT NULL);


--
-- Name: idx_issues_project_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_project_status ON public.issues USING btree (project_id, status_id, rank);


--
-- Name: idx_issues_sprint; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_issues_sprint ON public.issues USING btree (sprint_id);


--
-- Name: idx_notifications_email_pending; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_email_pending ON public.notifications USING btree (created_at) WHERE (email_state = 'pending'::text);


--
-- Name: idx_notifications_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user ON public.notifications USING btree (user_id, created_at DESC);


--
-- Name: idx_notifications_user_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user_unread ON public.notifications USING btree (user_id, created_at DESC) WHERE (read_at IS NULL);


--
-- Name: idx_project_members_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_project_members_user ON public.project_members USING btree (user_id);


--
-- Name: idx_projects_department; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_projects_department ON public.projects USING btree (department_id);


--
-- Name: idx_sprints_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sprints_project ON public.sprints USING btree (project_id, created_at);


--
-- Name: issue_templates_name_uk; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX issue_templates_name_uk ON public.issue_templates USING btree (project_id, lower(name));


--
-- Name: uq_sprints_one_active_per_project; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_sprints_one_active_per_project ON public.sprints USING btree (project_id) WHERE (status = 'active'::text);


--
-- Name: users_ldap_dn_uk; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_ldap_dn_uk ON public.users USING btree (lower(ldap_dn)) WHERE (ldap_dn IS NOT NULL);


--
-- Name: activity activity_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity
    ADD CONSTRAINT activity_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id);


--
-- Name: activity activity_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity
    ADD CONSTRAINT activity_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: attachments attachments_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: attachments attachments_uploaded_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: audit_log audit_log_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: checklist_items checklist_items_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_items
    ADD CONSTRAINT checklist_items_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: comments comments_author_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_author_id_fkey FOREIGN KEY (author_id) REFERENCES public.users(id);


--
-- Name: comments comments_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: custom_field_values custom_field_values_custom_field_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_field_values
    ADD CONSTRAINT custom_field_values_custom_field_id_fkey FOREIGN KEY (custom_field_id) REFERENCES public.custom_fields(id) ON DELETE CASCADE;


--
-- Name: custom_field_values custom_field_values_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_field_values
    ADD CONSTRAINT custom_field_values_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: custom_fields custom_fields_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.custom_fields
    ADD CONSTRAINT custom_fields_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: department_members department_members_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_members
    ADD CONSTRAINT department_members_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id) ON DELETE CASCADE;


--
-- Name: department_members department_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department_members
    ADD CONSTRAINT department_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: issue_collaborators issue_collaborators_added_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_collaborators
    ADD CONSTRAINT issue_collaborators_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: issue_collaborators issue_collaborators_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_collaborators
    ADD CONSTRAINT issue_collaborators_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: issue_collaborators issue_collaborators_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_collaborators
    ADD CONSTRAINT issue_collaborators_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: issue_links issue_links_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_links
    ADD CONSTRAINT issue_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: issue_links issue_links_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_links
    ADD CONSTRAINT issue_links_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: issue_links issue_links_linked_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_links
    ADD CONSTRAINT issue_links_linked_issue_id_fkey FOREIGN KEY (linked_issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: issue_templates issue_templates_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_templates
    ADD CONSTRAINT issue_templates_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: issue_templates issue_templates_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_templates
    ADD CONSTRAINT issue_templates_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.workflow_statuses(id) ON DELETE SET NULL;


--
-- Name: issue_watchers issue_watchers_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_watchers
    ADD CONSTRAINT issue_watchers_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: issue_watchers issue_watchers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issue_watchers
    ADD CONSTRAINT issue_watchers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: issues issues_assignee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: issues issues_epic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_epic_id_fkey FOREIGN KEY (epic_id) REFERENCES public.issues(id) ON DELETE SET NULL;


--
-- Name: issues issues_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.issues(id) ON DELETE SET NULL;


--
-- Name: issues issues_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: issues issues_reporter_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.users(id);


--
-- Name: issues issues_sprint_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_sprint_id_fkey FOREIGN KEY (sprint_id) REFERENCES public.sprints(id) ON DELETE SET NULL;


--
-- Name: issues issues_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.issues
    ADD CONSTRAINT issues_status_id_fkey FOREIGN KEY (status_id) REFERENCES public.workflow_statuses(id);


--
-- Name: notifications notifications_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: notifications notifications_issue_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: project_counters project_counters_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_counters
    ADD CONSTRAINT project_counters_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: project_members project_members_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: project_members project_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project_members
    ADD CONSTRAINT project_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: projects projects_department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.projects
    ADD CONSTRAINT projects_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id);


--
-- Name: sprints sprints_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprints
    ADD CONSTRAINT sprints_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: workflow_statuses workflow_statuses_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_statuses
    ADD CONSTRAINT workflow_statuses_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: workflow_transitions workflow_transitions_from_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transitions
    ADD CONSTRAINT workflow_transitions_from_status_id_fkey FOREIGN KEY (from_status_id) REFERENCES public.workflow_statuses(id) ON DELETE CASCADE;


--
-- Name: workflow_transitions workflow_transitions_project_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transitions
    ADD CONSTRAINT workflow_transitions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;


--
-- Name: workflow_transitions workflow_transitions_to_status_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_transitions
    ADD CONSTRAINT workflow_transitions_to_status_id_fkey FOREIGN KEY (to_status_id) REFERENCES public.workflow_statuses(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

INSERT INTO public.schema_migrations(name) VALUES
  ('001_init.sql'),
  ('002_corporate.sql'),
  ('003_counters.sql'),
  ('004_project_roles.sql'),
  ('006_drop_access_role.sql'),
  ('007_departments.sql'),
  ('008_issue_collaborators.sql'),
  ('009_ldap.sql'),
  ('010_attachments.sql'),
  ('011_notifications.sql'),
  ('012_drop_sprints.sql'),
  ('013_priority_four_levels.sql'),
  ('014_issue_links.sql'),
  ('015_notification_dismiss.sql'),
  ('016_issue_lifecycle.sql'),
  ('017_token_revocation.sql'),
  ('018_issue_complexity.sql'),
  ('019_checklist_items.sql'),
  ('020_custom_fields.sql'),
  ('021_subtasks.sql'),
  ('022_issue_templates.sql'),
  ('023_sprints.sql');

CREATE TABLE public.upgrade_snapshot_probe (value text PRIMARY KEY);
INSERT INTO public.upgrade_snapshot_probe(value) VALUES ('023_sprints.sql');
