/**
 * ТЗ 2.4: документация, которую можно породить из кода, порождается скриптом (а не поддерживается руками):
 *   docs/MIGRATION-LIST.md — список миграций (имя файла + первая содержательная строка комментария);
 *   docs/API-SCHEMAS.md    — справочник форм запросов и ответов из zod-схем server/src/contract.ts.
 * Таблица прав — отдельный генератор (scripts/generate-permissions.mjs, ТЗ 2.2).
 *
 *   npm run docs:generate   — записать файлы
 *   npm run docs:check      — упасть (код 1), если файлы не совпадают с кодом (CI, джоба `types`)
 *
 * Запускается через tsx из server/node_modules (contract.ts — TypeScript). Вывод детерминирован: без дат и git.
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const norm = (s: string) => s.replace(/\r\n/g, "\n");

/* ---------------- миграции ---------------- */
function migrationList(): string {
  const dir = join(root, "server", "migrations");
  const files = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort();
  const summary = (file: string): string => {
    const lines = norm(readFileSync(join(dir, file), "utf8")).split("\n");
    for (const raw of lines) {
      const l = raw.replace(/^\s*--+\s?/, "").trim();
      if (!raw.trim().startsWith("--")) break; // шапка кончилась
      if (!l || /^=+$/.test(l) || /^-+$/.test(l)) continue;
      if (/^Применяется server\/src\/db\.ts/i.test(l)) continue;
      return l.replace(/^Taskira\.\s*/i, "").replace(/\|/g, "\\|").slice(0, 200);
    }
    return "";
  };
  const legacy = files.filter((f) => /^\d{3}_/.test(f));
  const stamped = files.filter((f) => !/^\d{3}_/.test(f));
  const rows = (fs: string[]) => fs.map((f) => `| \`${f}\` | ${summary(f)} |`).join("\n");
  return `<!-- GENERATED by scripts/generate-docs.ts from server/migrations/*.sql — DO NOT EDIT. -->
# Список миграций

Порождается скриптом (\`npm run docs:generate\`), руками не редактируется. Правила написания миграций — в
[MIGRATIONS.md](./MIGRATIONS.md): исторические \`001\`–\`029\` неизменяемы, новые файлы — с префиксом-меткой времени.

## Исторические (последовательные)

| Файл | Первая строка описания |
|---|---|
${rows(legacy)}

## С меткой времени

| Файл | Первая строка описания |
|---|---|
${rows(stamped)}
`;
}

/* ---------------- zod → markdown ---------------- */
type Def = { typeName: string; [k: string]: unknown };
const defOf = (s: unknown): Def => (s as { _def: Def })._def;

function describe(schema: unknown): { type: string; optional: boolean; nullable: boolean; note: string } {
  let s: any = schema;
  let optional = false;
  let nullable = false;
  const notes: string[] = [];
  for (let i = 0; i < 12; i++) {
    const d = defOf(s);
    if (d.typeName === "ZodOptional") { optional = true; s = d.innerType; continue; }
    if (d.typeName === "ZodNullable") { nullable = true; s = d.innerType; continue; }
    if (d.typeName === "ZodDefault") { optional = true; notes.push(`по умолчанию ${JSON.stringify((d.defaultValue as () => unknown)())}`); s = d.innerType; continue; }
    if (d.typeName === "ZodEffects") { s = d.schema; continue; }
    if (d.typeName === "ZodBranded" || d.typeName === "ZodReadonly") { s = d.type ?? d.innerType; continue; }
    break;
  }
  const d = defOf(s);
  let type: string;
  switch (d.typeName) {
    case "ZodString": {
      type = "string";
      const c = ((d.checks as { kind: string; value?: number }[]) ?? []);
      const min = c.find((x) => x.kind === "min")?.value;
      const max = c.find((x) => x.kind === "max")?.value;
      const kinds = c.map((x) => x.kind).filter((k) => ["uuid", "email", "datetime", "url"].includes(k));
      if (kinds.length) type = `string (${kinds.join(", ")})`;
      if (min !== undefined || max !== undefined) notes.push(`длина ${min ?? 0}…${max ?? "∞"}`);
      break;
    }
    case "ZodNumber": {
      type = "number";
      const c = ((d.checks as { kind: string; value?: number }[]) ?? []);
      if (c.some((x) => x.kind === "int")) type = "integer";
      const min = c.find((x) => x.kind === "min")?.value;
      const max = c.find((x) => x.kind === "max")?.value;
      if (min !== undefined || max !== undefined) notes.push(`${min ?? "−∞"}…${max ?? "∞"}`);
      break;
    }
    case "ZodBoolean": type = "boolean"; break;
    case "ZodEnum": type = `enum: ${(d.values as string[]).map((v) => `\`${v}\``).join(" \\| ")}`; break;
    case "ZodNativeEnum": type = "enum"; break;
    case "ZodLiteral": type = `\`${JSON.stringify(d.value)}\``; break;
    case "ZodArray": type = `array&lt;${describe(d.type).type}&gt;`; break;
    case "ZodRecord": type = `record&lt;string, ${describe(d.valueType).type}&gt;`; break;
    case "ZodUnion": type = (d.options as unknown[]).map((o) => describe(o).type).join(" \\| "); break;
    case "ZodObject": type = "object"; break;
    case "ZodAny": case "ZodUnknown": type = "any"; break;
    default: type = String(d.typeName).replace(/^Zod/, "").toLowerCase();
  }
  return { type, optional, nullable, note: notes.join("; ") };
}

function objectShape(schema: unknown): Record<string, unknown> | null {
  let s: any = schema;
  for (let i = 0; i < 12; i++) {
    const d = defOf(s);
    if (d.typeName === "ZodObject") return (s as { shape: Record<string, unknown> }).shape;
    if (d.typeName === "ZodEffects") { s = d.schema; continue; }
    if (d.typeName === "ZodOptional" || d.typeName === "ZodNullable" || d.typeName === "ZodDefault") { s = d.innerType; continue; }
    return null;
  }
  return null;
}

async function apiSchemas(): Promise<string> {
  const mod = (await import(pathToFileURL(join(root, "server", "src", "contract.ts")).href)) as Record<string, unknown>;
  const isZod = (v: unknown): boolean => typeof v === "object" && v !== null && "_def" in (v as object) && typeof (v as { safeParse?: unknown }).safeParse === "function";
  const names = Object.keys(mod).filter((k) => isZod(mod[k])).sort();
  const kindOf = (n: string) => (/(Dto|Result|Response)$/.test(n) || /^(SafeUser|ReportTotals|ReportRow|ReportPoint|NotifyPrefs)$/.test(n) ? "response" : "request");
  const section = (n: string): string => {
    const shape = objectShape(mod[n]);
    if (!shape) return `### ${n}\n\n\`${describe(mod[n]).type}\`\n`;
    const rows = Object.entries(shape).map(([field, sch]) => {
      const d = describe(sch);
      const flags = [d.optional ? "необязательное" : "", d.nullable ? "может быть null" : ""].filter(Boolean).join(", ");
      return `| \`${field}\` | ${d.type} | ${[flags, d.note].filter(Boolean).join("; ")} |`;
    });
    return `### ${n}\n\n| Поле | Тип | Замечания |\n|---|---|---|\n${rows.join("\n")}\n`;
  };
  const req = names.filter((n) => kindOf(n) === "request");
  const res = names.filter((n) => kindOf(n) === "response");
  return `<!-- GENERATED by scripts/generate-docs.ts from server/src/contract.ts — DO NOT EDIT. -->
# Справочник схем API

Порождается из zod-схем \`server/src/contract.ts\` (\`npm run docs:generate\`), руками не редактируется. Это формы
**данных** (тела и параметры запросов, типы ответов), а не список эндпоинтов и не рантайм-гарантия соответствия ответов
БД: схемы ответов — источник типов клиента и сервера, \`.parse()\` на границе не выполняется (см. CLAUDE.md, ТЗ 2.1).
Точный список маршрутов и их прав — в \`server/README.md\` и \`server/src/routes/\`.

## Запросы (тела, query, params)

${req.map(section).join("\n")}
## Ответы

${res.map(section).join("\n")}`;
}

const outputs: [string, string][] = [
  ["docs/MIGRATION-LIST.md", migrationList()],
  ["docs/API-SCHEMAS.md", await apiSchemas()],
];

if (process.argv.includes("--check")) {
  const stale = outputs.filter(([p, c]) => !existsSync(join(root, p)) || norm(readFileSync(join(root, p), "utf8")) !== c);
  if (stale.length) {
    process.stderr.write(`Порождаемая документация устарела: ${stale.map(([p]) => p).join(", ")}.\nЗапустите: npm run docs:generate\n`);
    process.exit(1);
  }
  console.log("docs: ok");
} else {
  for (const [p, c] of outputs) writeFileSync(join(root, p), c);
  console.log(`docs: записано ${outputs.length} файла`);
}
