#!/usr/bin/env bash
set -Eeuo pipefail

MODE="${1:-}"
VERSION="${2:-}"
case "$MODE" in
  source) ;;
  release)
    [ -n "$VERSION" ] || { echo "Usage: $0 release VERSION" >&2; exit 2; }
    ;;
  *) echo "Usage: $0 source | release VERSION" >&2; exit 2 ;;
esac

cat <<'EOF'
# Generated by scripts/render-compose.sh. Do not edit this file directly.
services:
  postgres:
EOF
if [ "$MODE" = "release" ]; then
  printf '    image: localhost/taskira-postgres:%s\n' "$VERSION"
else
  cat <<'EOF'
    image: postgres:16-alpine
EOF
fi
cat <<'EOF'
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-taskira}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required; see .env.example}
      POSTGRES_DB: ${POSTGRES_DB:-taskira}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-taskira} -d ${POSTGRES_DB:-taskira}"]
      interval: 5s
      timeout: 5s
      retries: 20

  server:
EOF
if [ "$MODE" = "release" ]; then
  printf '    image: localhost/taskira-server:%s\n' "$VERSION"
else
  cat <<'EOF'
    build:
      context: ./server
      args:
        TASKIRA_VERSION: ${TASKIRA_VERSION:-dev}
EOF
fi
cat <<'EOF'
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-taskira}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-taskira}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required (at least 32 characters); see .env.example}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?ADMIN_PASSWORD is required; see .env.example}
      ADMIN_NAME: ${ADMIN_NAME:-Administrator}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:8081}
      APP_BASE_URL: ${CORS_ORIGIN:-http://localhost:8081}
      TRUST_PROXY: ${TRUST_PROXY:-true}
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE:-false}
      SESSION_TTL_SECONDS: ${SESSION_TTL_SECONDS:-28800}
      SESSION_ROTATE_AFTER_SECONDS: ${SESSION_ROTATE_AFTER_SECONDS:-3600}
      ACCOUNT_LOCK_MAX_FAILURES: ${ACCOUNT_LOCK_MAX_FAILURES:-5}
      ACCOUNT_LOCK_SECONDS: ${ACCOUNT_LOCK_SECONDS:-900}
      STORAGE_DIR: /app/var/attachments
      STORAGE_DRIVER: ${STORAGE_DRIVER:-local}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT:-}
      STORAGE_S3_BUCKET: ${STORAGE_S3_BUCKET:-}
      STORAGE_S3_REGION: ${STORAGE_S3_REGION:-us-east-1}
      STORAGE_S3_ACCESS_KEY: ${STORAGE_S3_ACCESS_KEY:-}
      STORAGE_S3_SECRET_KEY: ${STORAGE_S3_SECRET_KEY:-}
      STORAGE_S3_FORCE_PATH_STYLE: ${STORAGE_S3_FORCE_PATH_STYLE:-true}
    volumes:
      - attachments:/app/var/attachments
EOF
cat <<'EOF'
    healthcheck:
      # Keep the legacy readiness alias so rollback images remain health-checkable.
      test: ["CMD", "node", "-e", "fetch('http://localhost:8080/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 15s

  client:
EOF
if [ "$MODE" = "release" ]; then
  printf '    image: localhost/taskira-client:%s\n' "$VERSION"
else
  cat <<'EOF'
    build:
      context: .
      args:
        VITE_API_URL: ${VITE_API_URL:-}
        VITE_APP_VERSION: ${TASKIRA_VERSION:-dev}
EOF
fi
cat <<'EOF'
    restart: unless-stopped
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "${CLIENT_PORT:-8081}:80"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://localhost/healthz"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 5s

volumes:
  pgdata:
  attachments:
EOF
